/* Calendar and Inicio share the activities array and its session storage. */
let calendarSelected=todayKey,calendarView='month';
const calendarDate=key=>new Date(key+'T12:00:00');
const calendarKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const calendarShift=(key,days)=>{const d=calendarDate(key);d.setDate(d.getDate()+days);return calendarKey(d);};
const calendarLabel=key=>calendarDate(key).toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
function calendarDays(key,view){const d=calendarDate(key);if(view==='month')d.setDate(1);d.setDate(d.getDate()-(d.getDay()+6)%7);const start=calendarKey(d);const count=view==='week'?7:Math.ceil(((calendarDate(key.slice(0,7)+'-01').getDay()+6)%7+new Date(d.getFullYear(),calendarDate(key).getMonth()+1,0).getDate())/7)*7;return Array.from({length:count},(_,i)=>calendarShift(start,i));}
function dayActivities(key){return activities.filter(a=>a.date===key).sort((a,b)=>a.time.localeCompare(b.time));}
function activityRows(key=todayKey){return dayActivities(key).map(a=>`<button type="button" class="activity agenda-activity activity-button" data-activity-id="${escapeHtml(a.id)}"><time>${escapeHtml(a.time)}</time><span><strong class="${a.completed?'activity-struck':''}">${escapeHtml(a.description)}</strong>${a.comment?`<small>${escapeHtml(a.comment)}</small>`:''}</span></button>`).join('')||`<p class="muted">${page==='agenda'?'No hay actividades para este día':'No tenés actividades para hoy.'}</p>`;}
function agendaScreen(){const days=calendarDays(calendarSelected,calendarView),month=calendarSelected.slice(0,7),label=calendarView==='month'?calendarDate(calendarSelected).toLocaleDateString('es-AR',{month:'long',year:'numeric'}).replace(' de ',' '):`${calendarDate(days[0]).toLocaleDateString('es-AR',{day:'numeric',month:'short'})} – ${calendarDate(days[6]).toLocaleDateString('es-AR',{day:'numeric',month:'short',year:'numeric'})}`;return `<nav class="agenda-breadcrumb" aria-label="Ruta de navegación"><a href="./">Inicio</a><span aria-hidden="true">›</span><span aria-current="page">Agenda</span></nav><section class="card agenda calendar-card"><div class="agenda-heading"><h2>Calendario ${calendarView==='month'?'mensual':'semanal'}</h2><button class="agenda-add" data-open-activity aria-label="Cargar nueva actividad">${icon('calendarPlus')}</button></div><div class="calendar-toolbar"><div class="segmented">${[['month','Mensual'],['week','Semanal']].map(([v,t])=>`<button class="${calendarView===v?'selected':''}" data-calendar-view="${v}" aria-pressed="${calendarView===v}">${t}</button>`).join('')}</div></div><div class="calendar-period-navigation"><button class="secondary" data-calendar-move="-1" aria-label="Período anterior">‹</button><h3 class="calendar-period" aria-live="polite">${label}</h3><button class="secondary" data-calendar-move="1" aria-label="Período siguiente">›</button></div><div class="calendar-grid ${calendarView==='week'?'calendar-week':''}" role="group" aria-label="Fechas del calendario">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<span class="calendar-weekday">${d}</span>`).join('')}${days.map(key=>{const rows=dayActivities(key),pending=rows.some(a=>!a.completed);return `<button class="calendar-day ${key===calendarSelected?'is-selected':''} ${key===todayKey?'is-today':''} ${key.slice(0,7)!==month&&calendarView==='month'?'outside-month':''}" data-calendar-date="${key}" aria-pressed="${key===calendarSelected}" ${key===todayKey?'aria-current="date"':''} aria-label="${calendarLabel(key)}${rows.length?`, ${rows.length} actividades, ${pending?'con pendientes':'todas finalizadas'}`:', sin actividades'}"><span>${calendarDate(key).getDate()}</span>${rows.length?`<i class="calendar-dot ${pending?'pending':'completed'}" aria-hidden="true"></i>`:''}</button>`;}).join('')}</div><p class="calendar-legend"><span><i class="calendar-dot pending"></i>Pendientes</span><span><i class="calendar-dot completed"></i>Finalizadas</span></p><section class="calendar-activities" aria-live="polite"><h3>${calendarLabel(calendarSelected)}</h3>${activityRows(calendarSelected)}</section></section>`;}
function refreshActivities(){document.querySelector('main').innerHTML=page==='agenda'?agendaScreen():home();}
function persistActivities(){try{sessionStorage.setItem('consultor-home-v1',JSON.stringify({links:usefulLinks,activities}));return true;}catch{return false;}}
function activityEditor(record){const d=opDialog(record?'Editar actividad':'Nueva actividad',`<form autocomplete="off"><label>Fecha<input class="input" name="date" type="date" required value="${record?.date||(page==='agenda'?calendarSelected:todayKey)}"></label><label>Horario<input class="input" name="time" type="time" required value="${record?.time||''}"></label><label>Descripción<input class="input" name="description" autocomplete="off" required value="${escapeHtml(record?.description||'')}"></label><label>Comentario<textarea class="input" name="comment" rows="2">${escapeHtml(record?.comment||'')}</textarea></label><p class="form-error" role="alert"></p><div class="form-footer"><button type="button" class="secondary" data-modal-close>Cancelar</button><button type="submit" class="primary">Aplicar</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.description=data.description.trim();data.comment=data.comment.trim();if(!data.description){d.querySelector('.form-error').textContent='Ingresá una descripción.';return;}const previous=record?{...record}:null,newRecord=record||{id:crypto.randomUUID(),completed:false};Object.assign(newRecord,data);if(!record)activities.push(newRecord);if(!persistActivities()){if(record)Object.assign(record,previous);else activities.splice(activities.indexOf(newRecord),1);d.querySelector('.form-error').textContent='No se pudo guardar la actividad. Intentá nuevamente.';return;}d.close();refreshActivities();showOpNotice(record?'Actividad actualizada.':'Actividad agregada.');};}
function activityDetails(record){const d=opDialog(record.description,`<p>${calendarLabel(record.date)} · ${escapeHtml(record.time)}</p>${record.comment?`<p>${escapeHtml(record.comment)}</p>`:''}<p>${record.completed?'Finalizada':'Pendiente'}</p><div class="activity-options">${record.completed?'':'<button class="primary" data-complete-activity>Marcar como finalizada</button>'}<div class="activity-secondary-actions"><button class="icon-action" data-edit-activity aria-label="Editar actividad" title="Editar actividad">${icon('pencil')}</button>${deleteControl('Eliminar','data-remove-activity')}</div></div>`);d.querySelector('[data-edit-activity]').onclick=()=>{d.close();activityEditor(record);};d.querySelector('[data-complete-activity]')?.addEventListener('click',()=>{record.completed=true;if(!persistActivities()){record.completed=false;showOpNotice('No se pudo guardar el cambio.');return;}d.close();refreshActivities();showOpNotice('Actividad finalizada.');});d.querySelector('[data-remove-activity]').onclick=()=>confirmDelete('¿Estás seguro de que querés eliminar esta actividad?',()=>{const index=activities.indexOf(record);activities.splice(index,1);if(!persistActivities()){activities.splice(index,0,record);showOpNotice('No se pudo guardar la eliminación. Intentá nuevamente.');return false;}d.close();refreshActivities();});}
{
  activities.forEach(a=>{if(!a.id)a.id=crypto.randomUUID();a.completed=!!a.completed;});
  if((page==='inicio'||page==='agenda')&&state==='datos')refreshActivities();
  document.addEventListener('click',e=>{if(e.target.closest('[data-open-activity]')){e.preventDefault();e.stopImmediatePropagation();activityEditor();return;}const row=e.target.closest('[data-activity-id]');if(row){const a=activities.find(a=>a.id===row.dataset.activityId);if(a)activityDetails(a);return;}const day=e.target.closest('[data-calendar-date]'),viewButton=e.target.closest('[data-calendar-view]'),move=e.target.closest('[data-calendar-move]');if(day)calendarSelected=day.dataset.calendarDate;else if(viewButton)calendarView=viewButton.dataset.calendarView;else if(e.target.closest('[data-calendar-today]'))calendarSelected=todayKey;else if(move){const step=Number(move.dataset.calendarMove);if(calendarView==='week')calendarSelected=calendarShift(calendarSelected,step*7);else{const d=calendarDate(calendarSelected),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+step);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));calendarSelected=calendarKey(d);}}else return;refreshActivities();},true);
}

