/* Shared portfolio presentation. Source column IDs stay stable even with blank headers. */
const portfolioHeaders=window.CONSULTOR_DEMO_DATA?.headers||[];
function columnLetter(i){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;}
const portfolioColumns=portfolioHeaders.map((label,i)=>({key:'c'+i,index:i,label:label||'Columna '+columnLetter(i),letter:columnLetter(i)}));
const legacyColumn={n:1,e:0,z:2,s:3,latlog:4,whatsapp:6,id:15,nombre:16,apellido:17,telefono1:19,survey:35,d:36,accept:49,blindaje:55};
let consultantSettings={};
window.getConsultorSettings=()=>consultantSettings;
function columnValue(s,key){const i=Number(key.slice(1));if(s.sourceValues)return String(s.sourceValues[i]??'');const alias=Object.keys(legacyColumn).find(k=>legacyColumn[k]===i);return String(s[alias]??'');}
function visibleDetailColumns(){return consultantSettings.detailColumns??portfolioColumns.map(c=>c.key);}
function visibleActionColumns(){return consultantSettings.actionColumns??['c1','c3','c16','c19','c22','c61'];}
window.restoreConsultorSettings=function(settings){consultantSettings=settings||{};cardPreferences=consultantSettings.card||{title:'c1',additional:'c36'};};
cardTitle=s=>columnValue(s,cardPreferences.title?.startsWith('c')?cardPreferences.title:'c'+(legacyColumn[cardPreferences.title]??1))||s.n||'Sin nombre';
cardAdditional=s=>{if(!cardPreferences.additional)return '';return columnValue(s,cardPreferences.additional.startsWith('c')?cardPreferences.additional:'c'+(legacyColumn[cardPreferences.additional]??36));};
function extraError(d,message){let p=d.querySelector('[data-extra-error]');if(!p){p=document.createElement('p');p.dataset.extraError='';p.className='form-error';p.setAttribute('role','alert');d.append(p);}p.textContent=message;}
async function saveExtra(d,change,success){const controls=[...d.querySelectorAll('button,input,textarea,select')];const previous=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{await window.saveConsultorExtra(change);success?.();showOpNotice('Cambios guardados.');}catch(error){extraError(d,error.message);}finally{controls.forEach((e,i)=>e.disabled=previous[i]);}}
function columnOptions(value,empty=false){return (empty?'<option value="">Sin texto adicional</option>':'')+portfolioColumns.map(c=>`<option value="${c.key}" ${value===c.key?'selected':''}>${opEscape(c.label)} · ${c.letter}</option>`).join('');}
function chooseColumns(kind,onSaved){let chosen=[...(kind==='detailColumns'?visibleDetailColumns():visibleActionColumns())];const d=opDialog('Elegir y ordenar columnas','',true);d.dataset.extraForm='';const body=document.createElement('div');d.append(body);function paint(){const order=[...chosen,...portfolioColumns.map(c=>c.key).filter(k=>!chosen.includes(k))];body.innerHTML=`<p class="muted">Marcá las columnas que querés mostrar. Usá las flechas para cambiar su orden.${kind==='detailColumns'?' Se aplica a todas las fichas; los campos vacíos no se muestran.':' Acción comercial, Mail e ID siempre se muestran.'}</p><div class="column-choice-list">${order.map(key=>{const c=portfolioColumns.find(c=>c.key===key);if(!c)return '';const pos=chosen.indexOf(key);return `<div class="column-choice"><label><input type="checkbox" class="live-check" data-column="${key}" ${pos>=0?'checked':''}>${opEscape(c.label)} <small>${c.letter}</small></label><div><button class="icon-action" data-move="-1" data-key="${key}" ${pos<=0?'disabled':''} aria-label="Subir ${opEscape(c.label)}">↑</button><button class="icon-action" data-move="1" data-key="${key}" ${pos<0||pos===chosen.length-1?'disabled':''} aria-label="Bajar ${opEscape(c.label)}">↓</button></div></div>`;}).join('')}</div><p class="form-error" data-extra-error role="alert"></p><div class="form-footer"><button class="secondary" data-modal-close>Cancelar</button><button class="primary" data-save-columns>Aplicar</button></div>`;}
paint();body.onchange=e=>{const key=e.target.dataset.column;if(!key)return;if(e.target.checked)chosen.push(key);else chosen=chosen.filter(k=>k!==key);paint();};body.onclick=e=>{const b=e.target.closest('[data-move]');if(b){const i=chosen.indexOf(b.dataset.key),j=i+Number(b.dataset.move);if(i>=0&&j>=0&&j<chosen.length){[chosen[i],chosen[j]]=[chosen[j],chosen[i]];paint();body.querySelector(`[data-key="${b.dataset.key}"][data-move="${b.dataset.move}"]`)?.focus();}}if(e.target.closest('[data-save-columns]'))saveExtra(d,{kind,columns:chosen},()=>{d.close();onSaved?.();});};}
columnDialog=()=>chooseColumns('actionColumns');
function actionTableColumns(){return [{key:'action',label:'Acción comercial'},{key:'c0',label:'Mail'},{key:'c15',label:'ID'},...visibleActionColumns().filter(k=>!['c0','c15'].includes(k)).map(k=>portfolioColumns.find(c=>c.key===k)).filter(Boolean)];}
function assignmentCell(a,c){if(c.key==='action')return a.action;const s=sellers.find(s=>opNorm(s.e)===opNorm(a.email));return s?columnValue(s,c.key):c.key==='c0'?a.email:'';}
renderActionResults=function(){const root=document.querySelector('#action-results');if(!root)return;const rows=filteredAssignments(),cols=actionTableColumns();root.innerHTML=`${actionSelection.size?`<div class="selection"><span>${actionSelection.size} asignaciones seleccionadas</span>${deleteControl('Eliminar','data-op="delete-assignments"')}</div>`:''}<p class="count">${rows.length} asignaciones</p>${rows.length?`<div class="table-wrap card"><table><thead><tr><th><input type="checkbox" class="live-check" data-assignment-all aria-label="Seleccionar todas las asignaciones filtradas" ${rows.every(a=>actionSelection.has(a.id))?'checked':''}></th>${cols.map(c=>`<th>${opEscape(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(a=>`<tr><td>${opCheckbox(a.id,actionSelection.has(a.id),'Seleccionar '+a.commerce+' '+a.action,'assignment')}</td>${cols.map(c=>`<td>${c.key==='action'?actionPill(opEscape(a.action),a.color):opEscape(assignmentCell(a,c))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="mobile-cards">${rows.map(a=>`<article class="card assignment"><div class="assignment-top">${actionPill(opEscape(a.action),a.color)}${opCheckbox(a.id,actionSelection.has(a.id),'Seleccionar '+a.commerce,'assignment')}</div><div class="detail-grid">${cols.slice(1).map(c=>`<div><small>${opEscape(c.label)}</small>${opEscape(assignmentCell(a,c))}</div>`).join('')}</div></article>`).join('')}</div>`:empty('No hay asignaciones para mostrar','Probá otra búsqueda o agregá una acción comercial.')}`;};
exportActions=function(){const cols=actionTableColumns(),safe=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv='\ufeff'+[cols.map(c=>c.label),...filteredAssignments().map(a=>cols.map(c=>assignmentCell(a,c)))].map(r=>r.map(safe).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='AccionesComerciales.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
sellerDetail=function(s){if(!s)return;const d=opDialog(cardTitle(s),'',true);d.classList.add('seller-detail-dialog','configured-detail');const id=s.id;function paint(){s=sellers.find(s=>s.id===id);const heading=d.querySelector('.section-head');heading.classList.add('detail-fixed-heading');heading.querySelector('h2').textContent=cardTitle(s);heading.querySelector('[data-fixed-info]')?.remove();heading.insertAdjacentHTML('beforeend',`<div data-fixed-info><div class="chips">${s.a.map(a=>actionPill(opEscape(a[0]),a[1])).join('')}</div><div class="mail">${opEscape(s.e)}<button class="icon-action" data-op="copy-mail" data-id="${opEscape(s.id)}" aria-label="Copiar mail">${icon('copy')}</button></div>${cardAdditional(s)?`<p class="muted">${opEscape(cardAdditional(s))}</p>`:''}${contactButtons(s)}</div>`);d.querySelector('[data-detail-body]')?.remove();d.insertAdjacentHTML('beforeend',`<div data-detail-body><div class="detail-tools"><button class="secondary" data-choose-detail>Elegir y ordenar columnas</button><button class="icon-action" data-edit-all aria-label="Editar datos del comercio">${icon('pencil')}</button></div><div class="detail-grid">${visibleDetailColumns().map(key=>{const c=portfolioColumns.find(c=>c.key===key),v=columnValue(s,key);return c&&v.trim()?`<div class="seller-field"><small>${opEscape(c.label)}</small><span>${opEscape(v)}</span>${c.index>=1&&c.index<=14?`<button class="icon-action" data-edit-field="${c.index}" aria-label="Editar ${opEscape(c.label)}">${icon('pencil')}</button>`:''}</div>`:'';}).join('')}</div></div>`);d.querySelector('[data-choose-detail]').onclick=()=>chooseColumns('detailColumns',paint);d.querySelector('[data-edit-all]').onclick=()=>editSellerField(s,null,paint);d.querySelectorAll('[data-edit-field]').forEach(b=>b.onclick=()=>editSellerField(s,Number(b.dataset.editField),paint));}paint();};
function editSellerField(s,index,after){const d=opDialog('Editar dato del comercio',`<form data-extra-form><label>Dato<select class="input" name="column">${portfolioColumns.filter(c=>c.index>=1&&c.index<=14).map(c=>`<option value="${c.index}" ${c.index===(index??1)?'selected':''}>${opEscape(c.label)} · ${c.letter}</option>`).join('')}</select></label><label>Valor<textarea class="input" name="value" rows="3" maxlength="10000">${opEscape(columnValue(s,'c'+(index??1)))}</textarea></label><p class="form-error" data-extra-error role="alert"></p><div class="form-footer"><button type="button" class="secondary" data-modal-close>Cancelar</button><button class="primary">Aplicar</button></div></form>`);const f=d.querySelector('form');f.elements.column.onchange=()=>f.elements.value.value=columnValue(s,'c'+f.elements.column.value);f.onsubmit=e=>{e.preventDefault();const col=Number(f.elements.column.value),value=f.elements.value.value.trim();if(col===4&&value&&!parseLatLog(value)){extraError(d,'Ingresá latitud y longitud separadas por una coma.');return;}saveExtra(d,{kind:'sellerField',sellerId:s.id,column:col,value},()=>{d.close();after();});};}
profileConfiguration=function(){const main=document.querySelector('main');main.innerHTML='';const profile=consultantSettings.profile||{};const cust=sellers.map(s=>columnValue(s,'c23')).find(Boolean)||'—';const section=document.createElement('section');section.className='card profile-config';section.innerHTML=`<h2>Perfil del consultor</h2><form data-extra-form data-profile><label>Nombre y apellido<input class="input" name="name" autocomplete="name" maxlength="200" value="${opEscape(profile.name||'')}"></label><label>Mail<input class="input" name="email" type="email" autocomplete="email" maxlength="320" value="${opEscape(profile.email||'')}"></label><label>Cust ID Consultor<input class="input" value="${opEscape(cust)}" readonly></label><p class="form-error" data-extra-error role="alert"></p><div class="form-footer"><button class="primary">Aplicar</button></div></form><hr><h2>Ficha de Sellers</h2><form data-extra-form data-card><label>Texto destacado<select name="title" class="input">${columnOptions(cardPreferences.title)}</select></label><label>Texto adicional<select name="additional" class="input">${columnOptions(cardPreferences.additional,true)}</select></label><p class="form-error" data-extra-error role="alert"></p><div class="form-footer"><button class="primary">Aplicar</button></div></form><img class="contact-reference" src="assets/contact-card-reference.png" alt="Referencia: texto destacado, mail, texto adicional y botones de contacto"></section>`;main.append(section);for(const [selector,kind] of [['[data-profile]','profile'],['[data-card]','card']]){const f=section.querySelector(selector);f.onsubmit=e=>{e.preventDefault();saveExtra(f,{kind,...Object.fromEntries(new FormData(f))});};}};
let geographicMap=null,mapLibraryPromise=null;
function mapLibrary(){if(window.L)return Promise.resolve(window.L);if(mapLibraryPromise)return mapLibraryPromise;mapLibraryPromise=new Promise((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';css.integrity='sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=';css.crossOrigin='';document.head.append(css);const js=document.createElement('script');js.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';js.integrity='sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=';js.crossOrigin='';js.onload=()=>resolve(window.L);js.onerror=()=>{mapLibraryPromise=null;js.remove();reject(Error('No se pudo cargar el mapa. Revisá tu conexión e intentá nuevamente.'));};document.head.append(js);});return mapLibraryPromise;}
const renderSellerList=renderSellerResults;
renderSellerResults=function(){geographicMap?.remove();geographicMap=null;if(sellerView!=='map'){renderSellerList();return;}const root=document.querySelector('#seller-results');if(!root)return;const rows=filteredSellers(),located=rows.filter(s=>parseLatLog(s.latlog)),missing=rows.filter(s=>!parseLatLog(s.latlog));const filter=document.querySelector('[data-op="seller-filters"]');if(filter)filter.innerHTML=icon('filter')+'Filtros'+(filterCount()?' ('+filterCount()+')':'');root.innerHTML=`<p class="count">${rows.length} comercios encontrados</p><div class="toolbar"><span>Con ubicación: ${located.length}</span><button class="mini" data-op="seller-unlocated" aria-expanded="${showUnlocated}">Sin ubicación: ${missing.length}</button></div><div class="legend"><span style="--dot:#292932">Sin aceptación</span><span style="--dot:#288450">Encuesta válida</span><span style="--dot:#cf5058">Sin encuesta válida</span><span style="--dot:#8c8c9c">Sin dato</span></div><div class="geographic-wrapper"><div class="geographic-map" aria-label="Mapa de comercios"></div><div class="map-selected-card"></div><p class="map-load-status" role="status">${located.length?'Cargando mapa…':'No hay comercios con ubicación válida.'}</p></div>${showUnlocated?missing.map(liveSellerCard).join(''):''}`;const host=root.querySelector('.geographic-map'),status=root.querySelector('.map-load-status'),card=root.querySelector('.map-selected-card');if(!located.length)return;
mapLibrary().then(L=>{if(!host.isConnected)return;geographicMap=L.map(host,{scrollWheelZoom:false});const layer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(geographicMap);layer.on('tileerror',()=>{status.hidden=false;status.textContent='No se pudo cargar parte del mapa. Podés abrir las ubicaciones desde las fichas.';});status.hidden=true;for(const s of located){const marker=L.marker(parseLatLog(s.latlog),{title:s.n,alt:'Ubicación de '+s.n,icon:L.divIcon({className:'seller-map-marker',html:`<span style="background:${sellerColor(s)}"></span>`,iconSize:[32,32],iconAnchor:[16,16]})}).addTo(geographicMap);marker.on('click',()=>{mapSelected=s.id;card.innerHTML=liveSellerCard(s);card.scrollIntoView({block:'nearest',behavior:'smooth'});});}const selected=located.find(s=>s.id===mapSelected);if(selected)card.innerHTML=liveSellerCard(selected);geographicMap.fitBounds(located.map(s=>parseLatLog(s.latlog)),{padding:[35,60],maxZoom:15});}).catch(e=>{if(host.isConnected)status.textContent=e.message;});};
